HMS/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # url(r'^', include('mainsite.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^mainsite/', include('mainsite.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainsite/urls.py
from django.conf.urls import url
from . import views

app_name = 'mainsite'

urlpatterns = [

    # /mainsite/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /mainsite/attendance/
    url(r'^attendance/$', views.AttendanceListView.as_view(), name='attendance'),

    # /mainsite/attendance/<staff_id>/
    url(r'^attendance/(?P<pk>[0-9a-f]{8}\-[0-9a-f]{4}\-4[0-9a-f]{3}\-[89ab][0-9a-f]{3}\-[0-9a-f]{12})/$', views.DetailView.as_view(), name='staff_detail'),
]

mainsite/models.py
import uuid
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator
from django.db import models
from datetime import date

class Job(models.Model):
    job_title = models.CharField(primary_key=True, max_length=100)

    def __str__ (self):
        return self.job_title


class Gender(models.Model):
    gender_title = models.CharField(primary_key=True, max_length=50)

    def __str__ (self):
        return self.gender_title


class AttendanceType(models.Model):
    attendance_value = models.FloatField(primary_key=True, validators=[MinValueValidator(0), MaxValueValidator(1.0)])
    attendance_value_name = models.CharField(max_length=100)

    def __str__ (self):
        return self.attendance_value_name


class Staff(models.Model):
    staff_name = models.CharField(max_length=200)
    staff_shortname = models.CharField(max_length=100)
    staff_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    staff_phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list
    staff_doj = models.DateField(("Date"), default=date.today)
    staff_salary = models.PositiveIntegerField()
    staff_job_title = models.ForeignKey(Job, on_delete=models.PROTECT)
    staff_gender = models.ForeignKey(Gender, on_delete=models.PROTECT)

    def __str__(self):
        return self.staff_name + ' - ' + str(self.pk)

class StaffAttendance(models.Model):
    staff_id = models.ForeignKey(Staff, on_delete=models.CASCADE)
    attendance_date = models.DateField("Date")
    staff_attendance_value = models.ForeignKey(AttendanceType, on_delete=models.DO_NOTHING)

    def __str__ (self):
        return str(self.staff_id) + '-' + str(self.attendance_date) + '-' + str(self.staff_attendance_value)

mainsite/views.py
from django.views import generic
from django.views.generic import TemplateView
from .models import Staff, AttendanceType


class IndexView(TemplateView):
    template_name = 'mainsite/index.html'

class AttendanceListView(TemplateView):
    template_name = 'mainsite/attendance.html'

    def get_context_data(self, **kwargs):
        context = super(AttendanceListView, self).get_context_data(**kwargs)
        context['all_staffs'] = Staff.objects.all()
        context['all_attendance_types'] = AttendanceType.objects.all()
        return context



    #
    # template_name = ''
    # context_object_name = 'all_staffs'
    #
    # def get_queryset(self):
    #     return Staff.objects.all()

class DetailView(generic.DetailView):
    model = Staff
    template_name = 'mainsite/staff_detail.html'

mainsite/templates/mainsite/attendance.html
{% extends 'mainsite/base.html' %}
{% block title %} HMS : Attendance {% endblock %}
{% block item1_active %}active{% endblock %}
{% block extra_links %}
    <!-- Bootstrap Date-Picker Plugin -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
{% endblock %}

{% block body %}
<div class="container-fluid">
<form>

<div>
    <div class="row" >
            <div class="col-sm-4"></div>
                 <div class='col-sm-4' align="center">
                    <div class="form-group">
                        <div class='input-group date' id='datetimepicker1'>
                            <input type='text' class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                 <div class="col-sm-4">


                 </div>
            </div>
    </div>

    <div class="container">
        <div class="row">
            <div class='col-sm-6'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker1'>
                        <input type='text' class="form-control" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
            </div>
            <!--<script type="text/javascript">-->
                <!--$(function () {-->
                    <!--$('#datetimepicker1').datetimepicker();-->
                <!--});-->
            <!--</script>-->
        </div>
    </div>



    <div class="card-body">
      <div class="table-responsive ">
        <table class="table table-hover" id="dataTable" width="75%" cellspacing="0">
          <thead>
            <tr class="table-info">
              <th>#</th>
              <th>Name</th>
              <th>Job Title</th>
              <th>Attendance</th>
            </tr>
          </thead>
          {% if all_staffs %}
              {% for staff in all_staffs %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ staff.staff_name }}</td>
                  <td>{{ staff.staff_job_title }}</td>
                  <td>

                      <div class="btn-group btn-group-toggle" data-toggle="buttons">
                            {% for attendance_type in all_attendance_types %}
                                <!--<label class="btn btn-outline-info">-->
                                    {% if attendance_type.attendance_value == 1.0 %}
                                        <label class="btn btn-outline-info active">
                                            <input type="radio" name="attendance-{{ staff.staff_id }}" value="{{ attendance_type.attendance_value }}">
                                        <!--</label>-->
                                    {% else %}
                                        <label class="btn btn-outline-info">
                                            <input type="radio" name="attendance-{{ staff.staff_id }}" value="{{ attendance_type.attendance_value }}" >
                                        <!--</label>-->
                                    {% endif %}
                                    {{ attendance_type.attendance_value_name }}
                                </label>
                            {% endfor %}
                        </div>
                  </td>
                </tr>
              {% endfor %}

          {% else %}
                For loop not working
          {% endif %}

        </table>
      </div>
        <div class="row" >
            <div class="col-sm-4"></div>
                 <div class='col-sm-4' align="center">
                    <div class="form-group">
                        <div class='input-group date' id='datetimepicker1'>
                            <input type='text' class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                     <button class="btn btn-lg">Submit</button>
                </div>
                 <div class="col-sm-4">


                 </div>
            </div>
        <br/><br/><br/><br/><br/>
        </div>

  </div>
</form>
</div>








<div class="albums-container container-fluid">

    <!-- Staffs -->
    <div class="row">
        <div class="col-sm-12">
            <!--<h3>{{ user.username }}'s Albums</h3>-->
        </div>
        {% if all_staffs %}
            {% for staff in all_staffs %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <!--<a href="#">-->
                            <!--<img src="{{ album.album_logo.url }}" class="img-responsive">-->
                        <!--</a>-->
                        <div class="caption">
                            <h2>{{ staff.staff_name }}</h2>
                            <h6>{{ staff.id }}</h6>

                            <!-- View Details -->
                            <a href="{% url 'mainsite:staff_detail' staff.staff_id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="#" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                 <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>


                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <!--<a href="{% url 'mainsite:staff-add' %}">-->
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Staff
                    </button>
                <!--</a>-->
            </div>
        {% endif %}
    </div>

    <!--&lt;!&ndash; If user searches and there are songs &ndash;&gt;-->
    <!--{% if songs %}-->
        <!--<div class="row">-->
            <!--<div class="col-sm-12">-->
                <!--<h3>Songs</h3>-->
            <!--</div>-->
            <!--<div class="col-sm-12">-->
                <!--<div class="panel panel-default">-->
                    <!--<div class="panel-body">-->
                        <!--<table class="table">-->
                            <!--<thead>-->
                                <!--<tr>-->
                                    <!--<th>Song Title</th>-->
                                    <!--<th>Artist</th>-->
                                    <!--<th>Audio File</th>-->
                                    <!--<th>Album</th>-->
                                    <!--<th>Favorite</th>-->
                                <!--</tr>-->
                            <!--</thead>-->
                            <!--<tbody>-->
                                <!--{% for song in songs %}-->
                                    <!--<tr>-->
                                        <!--<td>{{ song.song_title }}</td>-->
                                        <!--<td>{{ song.album.artist }}</td>-->
                                        <!--<td>-->
                                            <!--<a target="_blank" href="{{ song.audio_file.url }}">-->
                                                <!--<button type="button" class="btn btn-success btn-xs">-->
                                                    <!--<span class="glyphicon glyphicon-play"></span>&nbsp; Play-->
                                                <!--</button>-->
                                            <!--</a>-->
                                        <!--</td>-->
                                        <!--<td>-->
                                            <!--<a href="{% url 'music:detail' song.album.id %}">-->
                                                <!--<img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />-->
                                            <!--</a>-->
                                            <!--<a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>-->
                                        <!--</td>-->
                                        <!--<td>-->
                                            <!--<a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>-->
                                        <!--</td>-->
                                    <!--</tr>-->
                                <!--{% endfor %}-->
                            <!--</tbody>-->
                        <!--</table>-->
                    <!--</div>-->
                <!--</div>-->
            <!--</div>-->
        <!--</div>-->
    <!--{% endif %}-->

</div>
{% endblock %}

mainsite/templates/mainsite/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" href="https://bootswatch.com/_vendor/bootstrap/dist/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>﻿
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% block extra_links %}{% endblock %}
    </head>
<body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <div class="container">
            <!--<a class="navbar-header" href="{% url 'mainsite:index' %}"><strong>HMS</strong></a>-->
            <!--<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">-->
                <!--<span class="navbar-toggler-icon"></span>-->
            <!--</button>-->

            <div class="collapse navbar-collapse" id="navbarColor03">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item {% block item0_active %}{% endblock %}">
                        <a class="nav-link" href="{% url 'mainsite:index' %}"><strong> HMS </strong><span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item {% block item1_active %}{% endblock %}">
                        <a class="nav-link" href="{% url 'mainsite:attendance' %}">Attendance</a>
                    </li>
                    <li class="nav-item {% block item2_active %}{% endblock %}">
                        <a class="nav-link" href="#">Item2</a>
                    </li>
                    <li class="nav-item {% block item3_active %}{% endblock %}">
                        <a class="nav-link" href="#">Item 3</a>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0" role="search" method="get" action="#>
                    <div class="form-group">
                        <input class="form-control mr-sm-2" placeholder="Search" type="text" name="q" value="">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </div>
                </form>

                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="#" target="_blank">Logout</a>
                    </li>
                    <!--<li class="nav-item">-->
                        <!--<a class="nav-link" href="https://wrapbootstrap.com/?ref=bsw" target="_blank">WrapBootstrap</a>-->
                    <!--</li>-->
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <br>
    <br>
    <br>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

mainsite/templates/mainsite/index.html
{% extends 'mainsite/base.html' %}
{% block title %}{{ HomePage }}{% endblock %}

{% block body %}
    <h2> Welcome to HMS</h2>
{% endblock %}

mainsite/templates/mainsite/staff_detail.html
{% extends 'mainsite/base.html' %}
{% block title %}{{ Attendance }}{% endblock %}
{% block item1_active %}active{% endblock %}
{% load static %}

{% block body %}
<div class="container-fluid songs-container">


    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">

                        <img src="{% static 'mainsite/images/Male.png' %}" class="img-responsive col-xs-10">

                    <h1>{{ staff.staff_name}} <small>{{ staff.staff_job_title}}</small></h1>
                    <h6>{{ staff.staff_id }}</h6>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}